// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0OOrSKsSWeEJt-7fdw6eUSboO1Nd3yNk',
    appId: '1:886863654305:web:255b80150f2ef1ef39efe0',
    messagingSenderId: '886863654305',
    projectId: 'tasckbase',
    authDomain: 'tasckbase.firebaseapp.com',
    storageBucket: 'tasckbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0MKfHaN-qNUeqZ3l7XYHefSAomqxOIYY',
    appId: '1:886863654305:android:f9b77297fcbd776b39efe0',
    messagingSenderId: '886863654305',
    projectId: 'tasckbase',
    storageBucket: 'tasckbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxGq2qn1daVqCEgBjA7I5NIT0TvPxJ6Z0',
    appId: '1:886863654305:ios:32eee44d94b7904239efe0',
    messagingSenderId: '886863654305',
    projectId: 'tasckbase',
    storageBucket: 'tasckbase.firebasestorage.app',
    iosBundleId: 'com.example.taskfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxGq2qn1daVqCEgBjA7I5NIT0TvPxJ6Z0',
    appId: '1:886863654305:ios:32eee44d94b7904239efe0',
    messagingSenderId: '886863654305',
    projectId: 'tasckbase',
    storageBucket: 'tasckbase.firebasestorage.app',
    iosBundleId: 'com.example.taskfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0OOrSKsSWeEJt-7fdw6eUSboO1Nd3yNk',
    appId: '1:886863654305:web:d84c46e68104cc2e39efe0',
    messagingSenderId: '886863654305',
    projectId: 'tasckbase',
    authDomain: 'tasckbase.firebaseapp.com',
    storageBucket: 'tasckbase.firebasestorage.app',
  );
}
